(self.AMP=self.AMP||[]).push({n:"amp-mustache",v:"2004252135000",f:(function(AMP,_){
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ia(a){for(var b=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var q=ia(this);function z(){z=function(){};q.Symbol||(q.Symbol=ja)}function ka(a,b){this.G=a;ha(this,"description",{configurable:!0,writable:!0,value:b})}ka.prototype.toString=function(){return this.G};
var ja=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ka("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function la(){z();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ha(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}});la=function(){}}
function ma(a){la();var b={next:a};b[q.Symbol.iterator]=function(){return this};return b}var na="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ua;if("function"==typeof Object.setPrototypeOf)ua=Object.setPrototypeOf;else{var va;a:{var wa={a:!0},xa={};try{xa.__proto__=wa;va=xa.a;break a}catch(a){}va=!1}ua=va?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ya=ua;function za(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function B(a){return a||{}};function Aa(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function Ba(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var Ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function Da(a){var b=Object.create(null);if(!a)return b;for(var c;c=Ca.exec(a);){var d=Ba(c[1],c[1]),e=c[2]?Ba(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var Ea="";var E=self.AMP_CONFIG||{},Fa=("string"==typeof E.cdnProxyRegex?new RegExp(E.cdnProxyRegex):E.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function Ga(a){if(!self.document||!self.document.head||self.location&&Fa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var Ha={thirdParty:E.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:E.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof E.thirdPartyFrameRegex?new RegExp(E.thirdPartyFrameRegex):E.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:E.cdnUrl||Ga("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:Fa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:E.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:E.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:E.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:E.geoApiUrl||Ga("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var Ia=self.__AMP_LOG;function F(){if(!Ia.user)throw Error("failed to call initLogConstructor");return Ia.user}function I(a,b,c){F().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function Ja(){var a=100;this.H=a;this.o=this.w=0;this.l=Object.create(null)}Ja.prototype.has=function(a){return!!this.l[a]};Ja.prototype.get=function(a){var b=this.l[a];if(b)return b.access=++this.o,b.payload};
Ja.prototype.put=function(a,b){this.has(a)||this.w++;this.l[a]={payload:b,access:this.o};if(!(this.w<=this.H)){if(Ia.dev)a=Ia.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.l;var c=this.o+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.w--)}};function L(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var Ua=B({c:!0,v:!0,a:!0,ad:!0,action:!0}),Va,Wa,Xa=/[?&]amp_js[^&]*/,Ya=/[?&]amp_gsa[^&]*/,Za=/[?&]amp_r[^&]*/,$a=/[?&]amp_kit[^&]*/,ab=/[?&]usqp[^&]*/;
function M(a){var b;Va||(Va=self.document.createElement("a"),Wa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new Ja));var c=b?null:Wa,d=Va;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=
e.hostname;e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=self;if(d.__AMP_MODE)d=d.__AMP_MODE;else{var f=self.AMP_CONFIG||{};var k=!!f.test||!1;var p=Da(d.location.originalHash||d.location.hash);f=f.spt;var t=Da(d.location.search);Ea||(Ea=d.AMP_CONFIG&&d.AMP_CONFIG.v?d.AMP_CONFIG.v:"012004252135000");k={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(p.development)||d.AMP_DEV_MODE),examiner:"2"==p.development,
esm:!1,geoOverride:p["amp-geo"],minified:!0,lite:void 0!=t.amp_lite,test:k,log:p.log,version:"2004252135000",rtvVersion:Ea,singlePassType:f};d=d.__AMP_MODE=k}e=d.test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,e);a=e}return a}function bb(a){"string"==typeof a&&(a=M(a));return Ha.cdnProxyRegex.test(a.origin)}
function cb(a){"string"==typeof a&&(a=M(a));if(!bb(a))return a.href;var b=a.pathname.split("/");I(Ua[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);I(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Xa,"").replace(Ya,"").replace(Za,"").replace($a,"").replace(ab,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function db(a,b){"string"==typeof b&&(b=M(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=M(d));c=c.replace(/\\/g,"/");var e=M(c);c=L(c.toLowerCase(),e.protocol)?e.href:L(c,"//")?d.protocol+c:L(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function eb(a){var b=M(a),c=Da(b.search);I(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};var fb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function gb(a){for(var b=[],c;c=fb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var k=c[3].toLowerCase();if("w"==k)e=parseInt(c[2],10);else if("x"==k)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new hb(b)}
function hb(a){I(0<a.length,"Srcset must have at least one source");this.j=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}I(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?ib:jb);this.F=b}
hb.prototype.select=function(a,b){if(this.F){b*=a;a=this.j;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var k=a[f].width,p=Math.abs(k-b);if(p<=1.1*d||1.2<b/e)c=f,d=p,e=k;else break}b=c}else{a=this.j;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.j[b].url};hb.prototype.getUrls=function(){return this.j.map(function(a){return a.url})};
hb.prototype.stringify=function(a){for(var b=[],c=this.j,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.F?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function ib(a,b){I(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function jb(a,b){I(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};function kb(a,b,c){return lb(b)?mb(a,b,c):c}function lb(a){return"src"==a||"href"==a||"xlink:href"==a||"srcset"==a}function mb(a,b,c){var d=self.location;eb(c);var e=bb(d),f=M(cb(d));if("href"==b&&!L(c,"#"))return db(c,f);if("src"==b)return"amp-img"==a?nb(c,f,e):db(c,f);if("srcset"==b){try{var k=gb(c)}catch(p){return F().error("URL-REWRITE","Failed to parse srcset: ",p),c}return k.stringify(function(a){return nb(a,f,e)})}return c}
function nb(a,b,c){a=M(db(a,b));return"data:"==a.protocol||bb(a)||!c?a.href:Ha.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var ob={"AMP-IMG":["src","srcset","layout","width","height"]};function pb(a,b){var c=L(a.tagName,"AMP-"),d=a.hasAttribute("i-amphtml-binding");if(!d&&ob[a.tagName])a.setAttribute("i-amphtml-ignore","");else if(d||c)a.hasAttribute("i-amphtml-key")||a.setAttribute("i-amphtml-key",b())}
var qb={applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,style:!0,video:!0},rb={"amp-accordion":!0,"amp-anim":!0,"amp-bind-macro":!0,"amp-carousel":!0,"amp-fit-text":!0,"amp-img":!0,"amp-layout":!0,"amp-selector":!0,"amp-sidebar":!0,"amp-timeago":!0},sb="a b br caption col colgroup code del div em hr i ins li mark ol p q s small span strong sub sup table tbody time td th thead tfoot tr u ul".split(" "),tb="amp-fx fallback heights layout min-font-size max-font-size on option placeholder submitting submit-success submit-error validation-for verify-error visible-when-invalid href style text subscriptions-action subscriptions-actions subscriptions-decorate subscriptions-dialog subscriptions-display subscriptions-section subscriptions-service amp-nested-submenu amp-nested-submenu-open amp-nested-submenu-close itemprop".split(" "),
ub={a:["rel","target"],div:["template"],form:["action-xhr","verify-xhr","custom-validation-reporting","target"],input:["mask-output"],template:["type"],textarea:["autoexpand"]},vb=["_top","_blank"],wb=/^(?:\w+script|data|blob):/i,Eb=/^(?:blob):/i,Fb=/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g,Gb=Object.freeze(B({input:{type:/(?:image|button)/i}})),Hb=Object.freeze(B({input:{type:/(?:button|file|image|password)/i}})),Ib=Object.freeze("form formaction formmethod formtarget formnovalidate formenctype".split(" ")),
Jb=Object.freeze(B({input:Ib,textarea:Ib,select:Ib})),Kb=Object.freeze(B({"amp-anim":["controls"],form:["name"]})),Lb=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function Mb(a,b,c,d){var e=!0;e=void 0===e?!1:e;var f=c?c.replace(Fb,""):"";if(!e){if(L(b,"on")&&"on"!=b)return!1;var k=f.toLowerCase();if(0<=k.indexOf("<script")||0<=k.indexOf("\x3c/script")||wb.test(f))return!1}if(Eb.test(f))return!1;if("style"==b)return!Lb.test(c);if("class"==b&&c&&/(^|\W)i-amphtml-/i.test(c)||lb(b)&&/__amp_source_origin/.test(c))return!1;var p=Aa(d),t=Object.assign(za(),Jb,p?Kb:{})[a];if(t&&-1!=t.indexOf(b))return!1;var w=Object.assign(za(),Gb,p?Hb:{})[a];if(w){var A=w[b];if(A&&
-1!=c.search(A))return!1}return!0};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Nb(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};var N=Object.freeze||function(a){return a},Ob=N("a abbr acronym address area article aside audio b bdi bdo big blink blockquote body br button canvas caption center cite code col colgroup content data datalist dd decorator del details dfn dir div dl dt element em fieldset figcaption figure font footer form h1 h2 h3 h4 h5 h6 head header hgroup hr html i img input ins kbd label legend li main map mark marquee menu menuitem meter nav nobr ol optgroup option output p pre progress q rp rt ruby s samp section select shadow small source spacer span strike strong style sub summary sup table tbody td template textarea tfoot th thead time tr track tt u ul var video wbr".split(" ")),
Pb=N("svg a altglyph altglyphdef altglyphitem animatecolor animatemotion animatetransform audio canvas circle clippath defs desc ellipse filter font g glyph glyphref hkern image line lineargradient marker mask metadata mpath path pattern polygon polyline radialgradient rect stop style switch symbol text textpath title tref tspan video view vkern".split(" ")),Qb=N("feBlend feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feMerge feMergeNode feMorphology feOffset fePointLight feSpecularLighting feSpotLight feTile feTurbulence".split(" ")),
Rb=N("math menclose merror mfenced mfrac mglyph mi mlabeledtr mmultiscripts mn mo mover mpadded mphantom mroot mrow ms mspace msqrt mstyle msub msup msubsup mtable mtd mtext mtr munder munderover".split(" ")),Sb=N(["#text"]),Tb=Object.freeze||function(a){return a},Ub=Tb("accept action align alt autocomplete background bgcolor border cellpadding cellspacing checked cite class clear color cols colspan controls coords crossorigin datetime default dir disabled download enctype face for headers height hidden high href hreflang id integrity ismap label lang list loop low max maxlength media method min minlength multiple name noshade novalidate nowrap open optimum pattern placeholder poster preload pubdate radiogroup readonly rel required rev reversed role rows rowspan spellcheck scope selected shape size sizes span srclang start src srcset step style summary tabindex title type usemap valign value width xmlns".split(" ")),
Vb=Tb("accent-height accumulate additive alignment-baseline ascent attributename attributetype azimuth basefrequency baseline-shift begin bias by class clip clip-path clip-rule color color-interpolation color-interpolation-filters color-profile color-rendering cx cy d dx dy diffuseconstant direction display divisor dur edgemode elevation end fill fill-opacity fill-rule filter filterunits flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight fx fy g1 g2 glyph-name glyphref gradientunits gradienttransform height href id image-rendering in in2 k k1 k2 k3 k4 kerning keypoints keysplines keytimes lang lengthadjust letter-spacing kernelmatrix kernelunitlength lighting-color local marker-end marker-mid marker-start markerheight markerunits markerwidth maskcontentunits maskunits max mask media method mode min name numoctaves offset operator opacity order orient orientation origin overflow paint-order path pathlength patterncontentunits patterntransform patternunits points preservealpha preserveaspectratio primitiveunits r rx ry radius refx refy repeatcount repeatdur restart result rotate scale seed shape-rendering specularconstant specularexponent spreadmethod stddeviation stitchtiles stop-color stop-opacity stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke stroke-width style surfacescale tabindex targetx targety transform text-anchor text-decoration text-rendering textlength type u1 u2 unicode values viewbox visibility version vert-adv-y vert-origin-x vert-origin-y width word-spacing wrap writing-mode xchannelselector ychannelselector x x1 x2 xmlns y y1 y2 z zoomandpan".split(" ")),
Wb=Tb("accent accentunder align bevelled close columnsalign columnlines columnspan denomalign depth dir display displaystyle encoding fence frame height href id largeop length linethickness lspace lquote mathbackground mathcolor mathsize mathvariant maxsize minsize movablelimits notation numalign open rowalign rowlines rowspacing rowspan rspace rquote scriptlevel scriptminsize scriptsizemultiplier selection separator separators stretchy subscriptshift supscriptshift symmetric voffset width xmlns".split(" ")),
Xb=Tb(["xlink:href","xml:id","xlink:title","xml:space","xmlns:xlink"]),Yb=Object.hasOwnProperty,Zb=Object.setPrototypeOf,$b=("undefined"!==typeof Reflect&&Reflect).apply;$b||($b=function(a,b,c){return a.apply(b,c)});function Q(a,b){Zb&&Zb(a,null);for(var c=b.length;c--;){var d=b[c];if("string"===typeof d){var e=d.toLowerCase();e!==d&&(Object.isFrozen(b)||(b[c]=e),d=e)}a[d]=!0}return a}function ac(a){var b={},c=void 0;for(c in a)$b(Yb,a,[c])&&(b[c]=a[c]);return b}
var R=Object.seal||function(a){return a},bc=R(/\{\{[\s\S]*|[\s\S]*\}\}/gm),cc=R(/<%[\s\S]*|[\s\S]*%>/gm),dc=R(/^data-[\-\w.\u00B7-\uFFFF]/),ec=R(/^aria-[\-\w]+$/),fc=R(/^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i),gc=R(/^(?:\w+script|data):/i),hc=R(/[\u0000-\u0020\u00A0\u1680\u180E\u2000-\u2029\u205f\u3000]/g);z();z();la();
var ic="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){z();z();z();return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};function X(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}return Array.from(a)}var jc=("undefined"!==typeof Reflect&&Reflect).apply,kc=Array.prototype.slice,lc=Object.freeze;jc||(jc=function(a,b,c){return a.apply(b,c)});
function mc(a,b){if("object"!==("undefined"===typeof a?"undefined":ic(a))||"function"!==typeof a.createPolicy)return null;var c=null,d="data-tt-policy-suffix";b.currentScript&&b.currentScript.hasAttribute(d)&&(c=b.currentScript.getAttribute(d));var e="dompurify"+(c?"#"+c:"");try{return a.createPolicy(e,{createHTML:function(a){return a}})}catch(f){return console.warn("TrustedTypes policy "+e+" could not be created."),null}}
function nc(){function a(a){var c,oa=void 0,h;d("beforeSanitizeAttributes",a,null);var e=a.attributes;if(e){var n={attrName:"",attrValue:"",keepAttr:!0,allowedAttributes:m};for(h=e.length;h--;){var da=c=e[h],f=da.name,g=da.namespaceURI;c=c.value.trim();var x=f.toLowerCase();n.attrName=x;n.attrValue=c;n.keepAttr=!0;d("uponSanitizeAttribute",a,n);c=n.attrValue;if("name"===x&&"IMG"===a.nodeName&&e.id)oa=e.id,e=jc(kc,e,[]),t("id",a),t(f,a),e.indexOf(oa)>h&&a.setAttribute("id",oa.value);else if("INPUT"!==
a.nodeName||"type"!==x||"file"!==c||!n.keepAttr||!m[x]&&O[x])"id"===f&&a.setAttribute(f,""),t(f,a);else continue;if(n.keepAttr)if(/svg|math/i.test(a.namespaceURI)&&(new RegExp("</("+Object.keys(yb).join("|")+")","i")).test(c))t(f,a);else{S&&(c=c.replace(bc," "),c=c.replace(cc," "));var C=a.nodeName.toLowerCase();if(b(C,x,c))try{g?a.setAttributeNS(g,f,c):a.setAttribute(f,c),l.removed.pop()}catch(Pc){}}}d("afterSanitizeAttributes",a,null)}}function b(a,b,c){if(zb&&("id"===b||"name"===b)&&(c in y||c in
Bc))return!1;if(!Ka||!dc.test(b))if(!H||!ec.test(b))if(!m[b]||O[b]||!(La[b]||Ma.test(c.replace(hc,""))||("src"===b||"xlink:href"===b||"href"===b)&&"script"!==a&&0===c.indexOf("data:")&&Cc[a]||Ab&&!gc.test(c.replace(hc,"")))&&c)return!1;return!0}function c(a){d("beforeSanitizeElements",a,null);if(f(a))return w(a),!0;var b=a.nodeName.toLowerCase();d("uponSanitizeElement",a,{tagName:b,allowedTags:v});if(("svg"===b||"math"===b)&&0!==a.querySelectorAll("p, br").length)return w(a),!0;if(!v[b]||pa[b]){if(Na&&
!yb[b]&&"function"===typeof a.insertAdjacentHTML)try{var c=a.innerHTML;a.insertAdjacentHTML("AfterEnd",n?n.createHTML(c):c)}catch(Nc){}w(a);return!0}if("noscript"===b&&/<\/noscript/i.test(a.innerHTML)||"noembed"===b&&/<\/noembed/i.test(a.innerHTML))return w(a),!0;!Bb||a.firstElementChild||a.content&&a.content.firstElementChild||!/</g.test(a.textContent)||(l.removed.push({element:a.cloneNode()}),a.innerHTML=a.innerHTML?a.innerHTML.replace(/</g,"&lt;"):a.textContent.replace(/</g,"&lt;"));S&&3===a.nodeType&&
(b=a.textContent,b=b.replace(bc," "),b=b.replace(cc," "),a.textContent!==b&&(l.removed.push({element:a.cloneNode()}),a.textContent=b));d("afterSanitizeElements",a,null);return!1}function d(a,b,c){G[a]&&G[a].forEach(function(a){a.call(l,b,c,T)})}function e(a){return"object"===("undefined"===typeof J?"undefined":ic(J))?a instanceof J:a&&"object"===("undefined"===typeof a?"undefined":ic(a))&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName}function f(a){return a instanceof Oa||a instanceof
Pa?!1:"string"===typeof a.nodeName&&"string"===typeof a.textContent&&"function"===typeof a.removeChild&&a.attributes instanceof qa&&"function"===typeof a.removeAttribute&&"function"===typeof a.setAttribute&&"string"===typeof a.namespaceURI?!1:!0}function k(a){return K.call(a.ownerDocument||a,a,U.SHOW_ELEMENT|U.SHOW_COMMENT|U.SHOW_TEXT,function(){return U.FILTER_ACCEPT},!1)}function p(a){var b=void 0,c=void 0;if(Qa)a="<remove></remove>"+a;else{var d=a.match(/^[\s]+/);(c=d&&d[0])&&(a=a.slice(c.length))}if(ra)try{b=
(new ba).parseFromString(a,"text/html")}catch(Oc){}P&&Q(pa,["title"]);if(!b||!b.documentElement){var h=b=C.createHTMLDocument("");d=h.body;d.parentNode.removeChild(d.parentNode.firstElementChild);d.outerHTML=n?n.createHTML(a):a}a&&c&&b.body.insertBefore(y.createTextNode(c),b.body.childNodes[0]||null);return Dc.call(b,ca?"html":"body")[0]}function t(a,b){try{l.removed.push({attribute:b.getAttributeNode(a),from:b})}catch(xb){l.removed.push({attribute:null,from:b})}b.removeAttribute(a)}function w(a){l.removed.push({element:a});
try{a.parentNode.removeChild(a)}catch(Ac){a.outerHTML=da}}function A(a){T&&T===a||(a&&"object"===("undefined"===typeof a?"undefined":ic(a))||(a={}),v="ALLOWED_TAGS"in a?Q({},a.ALLOWED_TAGS):u,m="ALLOWED_ATTR"in a?Q({},a.ALLOWED_ATTR):D,La="ADD_URI_SAFE_ATTR"in a?Q(ac(Cb),a.ADD_URI_SAFE_ATTR):Cb,pa="FORBID_TAGS"in a?Q({},a.FORBID_TAGS):{},O="FORBID_ATTR"in a?Q({},a.FORBID_ATTR):{},V="USE_PROFILES"in a?a.USE_PROFILES:!1,H=!1!==a.ALLOW_ARIA_ATTR,Ka=!1!==a.ALLOW_DATA_ATTR,Ab=a.ALLOW_UNKNOWN_PROTOCOLS||
!1,Bb=a.SAFE_FOR_JQUERY||!1,S=a.SAFE_FOR_TEMPLATES||!1,ca=a.WHOLE_DOCUMENT||!1,ea=a.RETURN_DOM||!1,Ra=a.RETURN_DOM_FRAGMENT||!1,Db=a.RETURN_DOM_IMPORT||!1,Sa=a.RETURN_TRUSTED_TYPE||!1,Qa=a.FORCE_BODY||!1,zb=!1!==a.SANITIZE_DOM,Na=!1!==a.KEEP_CONTENT,sa=a.IN_PLACE||!1,Ma=a.ALLOWED_URI_REGEXP||Ma,S&&(Ka=!1),Ra&&(ea=!0),V&&(v=Q({},[].concat(X(Sb))),m=[],!0===V.html&&(Q(v,Ob),Q(m,Ub)),!0===V.svg&&(Q(v,Pb),Q(m,Vb),Q(m,Xb)),!0===V.svgFilters&&(Q(v,Qb),Q(m,Vb),Q(m,Xb)),!0===V.mathMl&&(Q(v,Rb),Q(m,Wb),Q(m,
Xb))),a.ADD_TAGS&&(v===u&&(v=ac(v)),Q(v,a.ADD_TAGS)),a.ADD_ATTR&&(m===D&&(m=ac(m)),Q(m,a.ADD_ATTR)),a.ADD_URI_SAFE_ATTR&&Q(La,a.ADD_URI_SAFE_ATTR),Na&&(v["#text"]=!0),ca&&Q(v,["html","head","body"]),v.table&&(Q(v,["tbody"]),delete pa.tbody),lc&&lc(a),T=a)}function l(a){return nc(a)}var g=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"undefined"===typeof window?null:window;l.version="2.0.7";l.removed=[];if(!g||!g.document||9!==g.document.nodeType)return l.isSupported=!1,l;var r=g.document,
ra=!1,P=!1,y=g.document,ta=g.DocumentFragment,J=g.Node,U=g.NodeFilter,W=g.NamedNodeMap,qa=void 0===W?g.NamedNodeMap||g.MozNamedAttrMap:W,Oa=g.Text,Pa=g.Comment,ba=g.DOMParser;W=g.TrustedTypes;if("function"===typeof g.HTMLTemplateElement){var h=y.createElement("template");h.content&&h.content.ownerDocument&&(y=h.content.ownerDocument)}var n=mc(W,r),da=n?n.createHTML(""):"",x=y,C=x.implementation,K=x.createNodeIterator,Dc=x.getElementsByTagName,fa=x.createDocumentFragment,Ec=r.importNode,G={};l.isSupported=
C&&"undefined"!==typeof C.createHTMLDocument&&9!==y.documentMode;var Ma=fc,v=null,u=Q({},[].concat(X(Ob),X(Pb),X(Qb),X(Rb),X(Sb))),m=null,D=Q({},[].concat(X(Ub),X(Vb),X(Wb),X(Xb))),pa=null,O=null,H=!0,Ka=!0,Ab=!1,Bb=!1,S=!1,ca=!1,Ta=!1,Qa=!1,ea=!1,Ra=!1,Db=!1,Sa=!1,zb=!0,Na=!0,sa=!1,V={},yb=Q({},"annotation-xml audio colgroup desc foreignobject head iframe math mi mn mo ms mtext noembed noframes plaintext script style svg template thead title video xmp".split(" ")),Cc=Q({},["audio","video","img",
"source","image"]),La=null,Cb=Q({},"alt class for id label name pattern placeholder summary title value style xmlns".split(" ")),T=null,Bc=y.createElement("form");l.isSupported&&(function(){try{p('<svg><p><textarea><img src="</textarea><img src=x abc=1//">').querySelector("svg img")&&(ra=!0)}catch(oa){}}(),function(){try{var a=p("<x/><title>&lt;/title&gt;&lt;img&gt;");/<\/title/.test(a.querySelector("title").innerHTML)&&(P=!0)}catch(Ac){}}());var Fc=function xb(b){var h=void 0,e=k(b);for(d("beforeSanitizeShadowDOM",
b,null);h=e.nextNode();)d("uponSanitizeShadowNode",h,null),c(h)||(h.content instanceof ta&&xb(h.content),a(h));d("afterSanitizeShadowDOM",b,null)};l.sanitize=function(b,d){var h=void 0,f=void 0,x=void 0,C=void 0;b||(b="\x3c!--\x3e");if("string"!==typeof b&&!e(b)){if("function"!==typeof b.toString)throw new TypeError("toString is not a function");b=b.toString();if("string"!==typeof b)throw new TypeError("dirty is not a string, aborting");}if(!l.isSupported){if("object"===ic(g.toStaticHTML)||"function"===
typeof g.toStaticHTML){if("string"===typeof b)return g.toStaticHTML(b);if(e(b))return g.toStaticHTML(b.outerHTML)}return b}Ta||A(d);l.removed=[];if(!sa)if(b instanceof J)h=p("\x3c!--\x3e"),f=h.ownerDocument.importNode(b,!0),1===f.nodeType&&"BODY"===f.nodeName?h=f:"HTML"===f.nodeName?h=f:h.appendChild(f);else{if(!ea&&!S&&!ca&&Sa&&-1===b.indexOf("<"))return n?n.createHTML(b):b;h=p(b);if(!h)return ea?null:da}h&&Qa&&w(h.firstChild);for(var m=k(sa?b:h);d=m.nextNode();)3===d.nodeType&&d===x||c(d)||(d.content instanceof
ta&&Fc(d.content),a(d),x=d);x=null;if(sa)return b;if(ea){if(Ra)for(C=fa.call(h.ownerDocument);h.firstChild;)C.appendChild(h.firstChild);else C=h;Db&&(C=Ec.call(r,C,!0));return C}var K=ca?h.outerHTML:h.innerHTML;S&&(K=K.replace(bc," "),K=K.replace(cc," "));return n&&Sa?n.createHTML(K):K};l.setConfig=function(a){A(a);Ta=!0};l.clearConfig=function(){T=null;Ta=!1};l.isValidAttribute=function(a,c,d){T||A({});a=a.toLowerCase();c=c.toLowerCase();return b(a,c,d)};l.addHook=function(a,b){"function"===typeof b&&
(G[a]=G[a]||[],G[a].push(b))};l.removeHook=function(a){G[a]&&G[a].pop()};l.removeHooks=function(a){G[a]&&(G[a]=[])};l.removeAllHooks=function(){G={}};return l}var oc=nc();var pc={script:{attribute:"type",values:["application/json","application/ld+json"]}},qc={USE_PROFILES:{html:!0,svg:!0,svgFilters:!0}};function rc(a){var b={},c=kb;this.m=a;this.I=1;this.h=oc(self);this.A=oc(self);a=Object.assign(b||{},Object.assign({},qc,{ADD_ATTR:tb,ADD_TAGS:["use"],FORBID_TAGS:Object.keys(qb),FORCE_BODY:!0,RETURN_DOM:!0,ALLOW_UNKNOWN_PROTOCOLS:!0}));this.h.setConfig(a);sc(this,this.h,c);tc(this.A)}rc.prototype.purifyHtml=function(a){return this.h.sanitize(a)};
rc.prototype.purifyTagsForTripleMustache=function(a){a=this.A.sanitize(a,{ALLOWED_TAGS:sb,FORCE_BODY:!0,RETURN_DOM_FRAGMENT:!0});var b=this.m.createElement("div");b.appendChild(a);return b.innerHTML};rc.prototype.getAllowedTags=function(){var a={};this.h.addHook("uponSanitizeElement",function(b,d){Object.assign(a,d.allowedTags)});var b=this.m.createElement("p");this.h.sanitize(b);Object.keys(qb).forEach(function(b){a[b]=!1});this.h.removeHook("uponSanitizeElement");return a};
rc.prototype.validateAttributeChange=function(a,b,c){var d=a.nodeName.toLowerCase(),e=pc[d];if(e){var f=e,k=f.attribute;f=f.values;if(k===b&&(null==c||!f.includes(c)))return!1}if("a"===d&&"target"===b&&(null==c||!vb.includes(c)))return!1;if(null==c)return!0;if(uc(b)!==vc)return!1;var p=this.h.isValidAttribute(d,b,c);if(!p){var t=ub[d],w=t&&t.includes(b);if(!w&&!L(d,"amp-"))return!1}a=a.ownerDocument?a.ownerDocument:a;return c&&!Mb(d,b,c,a)?!1:!0};
function sc(a,b,c){function d(b){pb(b,function(){return String(a.I++)});l.forEach(function(a){delete A[a]});l.length=0;"use"===b.nodeName.toLowerCase()&&["href","xlink:href"].forEach(function(a){b.hasAttribute(a)&&!L(b.getAttribute(a),"#")&&(b.parentElement&&b.parentElement.removeChild(b),F().error("purifier",'Removed invalid <use>. use[href] must start with "#".'))})}function e(b,d){function e(){A[g]||(A[g]=!0,l.push(g))}var f=b.nodeName.toLowerCase(),g=d.attrName,k=d.attrValue;A=d.allowedAttributes;
if(L(f,"amp-"))e();else{if("a"==f&&"target"==g){var p=k.toLowerCase();k=vb.includes(p)?p:"_top"}var r=ub[f];r&&r.includes(g)&&e()}var t=uc(g);t===wc&&(r=g.substring(1,g.length-1),b.setAttribute("data-amp-bind-"+r,k));t!==vc&&b.setAttribute("i-amphtml-binding","");Mb(f,g,k,a.m)?c&&k&&!L(g,"data-amp-bind-")&&(k=c(f,g,k)):(d.keepAttr=!1,F().error("purifier",'Removed invalid attribute %s[%s="%s"].',f,g,k));d.attrValue=k}function f(){w.forEach(function(a){delete t[a]});w.length=0}function k(a,b){var c=
b.tagName;t=b.allowedTags;L(c,"amp-")&&(t[c]=!p||rb[c]);"a"===c&&a.hasAttribute("href")&&!a.hasAttribute("target")&&a.setAttribute("target","_top");var d=pc[c];d&&(b=d.attribute,d=d.values,a.hasAttribute(b)&&d.includes(a.getAttribute(b))&&(t[c]=!0,w.push(c)))}var p=Aa(a.m),t,w=[],A,l=[];b.addHook("uponSanitizeElement",k);b.addHook("afterSanitizeElements",f);b.addHook("uponSanitizeAttribute",e);b.addHook("afterSanitizeAttributes",d)}
function tc(a){var b;a.addHook("uponSanitizeElement",function(a,d){var c=d.tagName;b=d.allowedTags;"template"===c&&(a=a.getAttribute("type"))&&"amp-mustache"===a.toLowerCase()&&(b.template=!0)});a.addHook("afterSanitizeElements",function(){b.template=!1})}var vc=0,wc=1,xc=2;function uc(a){return"["==a[0]&&"]"==a[a.length-1]?wc:L(a,"data-amp-bind-")?xc:vc};function yc(a,b){var c,d=a=a.__AMP_TOP||(a.__AMP_TOP=a),e=a,f=zc(d),k=f.purifier;k||(k=f.purifier={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});k.ctor||k.obj||(k.ctor=b,k.context=e,k.resolve&&Gc(d));c&&Gc(a)}function Hc(a){a=a.__AMP_TOP||(a.__AMP_TOP=a);return Gc(a)}function Gc(a){var b=zc(a);a=b.purifier;a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function zc(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b};/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
var Ic={};
(function(a){function b(a){return"function"===typeof a}function c(a){return P(a)?"array":typeof a}function d(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function e(a,b){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,b)}function f(a,b){return y.call(a,b)}function k(a){return!f(ta,a)}function p(a){return String(a).replace(/[&<>"'`=\/]/g,function(a){return J[a]})}function t(b,c){function h(){if(fa&&!p)for(;g.length;)delete n[g.pop()];else g=[];p=fa=!1}function e(a){"string"===
typeof a&&(a=a.split(W,2));if(!P(a)||2!==a.length)throw Error("Invalid tags: "+a);t=new RegExp(d(a[0])+"\\s*");r=new RegExp("\\s*"+d(a[1]));v=new RegExp("\\s*"+d("}"+a[1]))}if(!b)return[];var f=[],n=[],g=[],fa=!1,p=!1,t,r,v;e(c||a.tags);for(var u=new l(b),m,D,y,O,H;!u.eos();){b=u.pos;if(D=u.scanUntil(t)){m=0;for(var J=D.length;m<J;++m)y=D.charAt(m),k(y)?g.push(n.length):p=!0,n.push(["text",y,b,b+1]),b+=1,"\n"===y&&h()}if(!u.scan(t))break;fa=!0;m=u.scan(Pa)||"name";u.scan(U);"="===m?(D=u.scanUntil(qa),
u.scan(qa),u.scanUntil(r)):"{"===m?(D=u.scanUntil(v),u.scan(Oa),u.scanUntil(r),m="&"):D=u.scanUntil(r);if(!u.scan(r))throw Error("Unclosed tag at "+u.pos);O=[m,D,b,u.pos];n.push(O);if("#"===m||"^"===m)f.push(O);else if("/"===m){H=f.pop();if(!H)throw Error('Unopened section "'+D+'" at '+b);if(H[1]!==D)throw Error('Unclosed section "'+H[1]+'" at '+b);}else if("name"===m||"{"===m||"&"===m)p=!0}if(H=f.pop())throw Error('Unclosed section "'+H[1]+'" at '+u.pos);return A(w(n))}function w(a){for(var b=[],
c,d,h=0,e=a.length;h<e;++h)if(c=a[h])"text"===c[0]&&d&&"text"===d[0]?(d[1]+=c[1],d[3]=c[3]):(b.push(c),d=c);return b}function A(a){for(var b=[],c=b,d=[],h,e,f=0,g=a.length;f<g;++f)switch(h=a[f],h[0]){case "#":case "^":c.push(h);d.push(h);c=h[4]=[];break;case "/":e=d.pop();e[5]=h[2];c=0<d.length?d[d.length-1][4]:b;break;default:c.push(h)}return b}function l(a){this.tail=this.string=a;this.pos=0}function g(a,b){this.view=a;this.cache={".":this.view};this.parent=b}function r(){this.cache={}}var ra=Object.prototype.toString,
P=Array.isArray||function(a){return"[object Array]"===ra.call(a)},y=RegExp.prototype.test,ta=/\S/,J={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},U=/\s*/,W=/\s+/,qa=/\s*=/,Oa=/\s*\}/,Pa=/#|\^|\/|>|\{|&|=|!/;l.prototype.eos=function(){return""===this.tail};l.prototype.scan=function(a){a=this.tail.match(a);if(!a||0!==a.index)return"";a=a[0];this.tail=this.tail.substring(a.length);this.pos+=a.length;return a};l.prototype.scanUntil=function(a){a=this.tail.search(a);
switch(a){case -1:var b=this.tail;this.tail="";break;case 0:b="";break;default:b=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=b.length;return b};g.prototype.push=function(a){return new g(a,this)};g.prototype.lookup=function(a){var c=this.cache;if(c.hasOwnProperty(a))var d=c[a];else{for(var h=this,f,g,k=!1;h;){if(0<a.indexOf("."))for(d=h.view,f=a.split("."),g=0;null!=d&&g<f.length;){if(!e(d,f[g])){d=null;break}g===f.length-1&&(k=!0);d=d[f[g++]]}else e(h.view,a)?(d=h.view[a],
k=!0):d=null;if(k)break;h=h.parent}c[a]=d}b(d)&&(d=d.call(this.view));return d};r.prototype.clearCache=function(){this.cache={}};r.prototype.parse=function(a,b){var c=this.cache,d=c[a];null==d&&(d=c[a]=t(a,b));return d};r.prototype.render=function(a,b,c){var d=this.parse(a);b=b instanceof g?b:new g(b);return this.renderTokens(d,b,c,a)};r.prototype.renderTokens=function(a,b,c,d){for(var e="",h,f,g,n=0,k=a.length;n<k;++n)g=void 0,h=a[n],f=h[0],"#"===f?g=this.renderSection(h,b,c,d):"^"===f?g=this.renderInverted(h,
b,c,d):">"===f?g=this.renderPartial(h,b,c,d):"&"===f?g=this.unescapedValue(h,b):"name"===f?g=this.escapedValue(h,b):"text"===f&&(g=this.rawValue(h)),void 0!==g&&(e+=g);return e};r.prototype.renderSection=function(a,c,d,e){function h(a){return f.render(a,c,d)}var f=this,g="",k=c.lookup(a[1]);if(k){if(P(k))for(var n=0,l=k.length;n<l;++n)g+=this.renderTokens(a[4],c.push(k[n]),d,e);else if("object"===typeof k||"string"===typeof k||"number"===typeof k)g+=this.renderTokens(a[4],c.push(k),d,e);else if(b(k)){if("string"!==
typeof e)throw Error("Cannot use higher-order sections without the original template");k=k.call(c.view,e.slice(a[3],a[5]),h);null!=k&&(g+=k)}else g+=this.renderTokens(a[4],c,d,e);return g}};r.prototype.renderInverted=function(a,b,c,d){var e=b.lookup(a[1]);if(!e||P(e)&&0===e.length)return this.renderTokens(a[4],b,c,d)};r.prototype.renderPartial=function(a,c,d){if(d&&(a=b(d)?d(a[1]):d[a[1]],null!=a))return this.renderTokens(this.parse(a),c,d,a)};r.prototype.unescapedValue=function(b,c){b=c.lookup(b[1]);
if(null!=b)return a.sanitizeUnescaped?a.sanitizeUnescaped(b):b};r.prototype.escapedValue=function(b,c){b=c.lookup(b[1]);if(null!=b)return a.escape(b)};r.prototype.rawValue=function(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var ba=new r;a.clearCache=function(){return ba.clearCache()};a.parse=function(a,b){return ba.parse(a,b)};a.render=function(a,b,d){if("string"!==typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+c(a)+'" was given as the first argument for mustache#render(template, view, partials)');
return ba.render(a,b,d)};a.to_html=function(c,d,e,f){c=a.render(c,d,e);if(b(f))f(c);else return c};a.escape=p;a.sanitizeUnescaped=null;a.setUnescapedSanitizer=function(b){a.sanitizeUnescaped=b};a.Scanner=l;a.Context=g;a.Writer=r})(Ic);var Y=AMP.BaseTemplate;function Z(a,b){var c=Y.call(this,a,b)||this;yc(b,function(){return new rc(b.document)});c.C=Hc(b);Ic.setUnescapedSanitizer(function(a){return c.C.purifyTagsForTripleMustache(a)});return c}Z.prototype=na(Y.prototype);Z.prototype.constructor=Z;if(ya)ya(Z,Y);else for(var Jc in Y)if("prototype"!=Jc)if(Object.defineProperties){var Kc=Object.getOwnPropertyDescriptor(Y,Jc);Kc&&Object.defineProperty(Z,Jc,Kc)}else Z[Jc]=Y[Jc];Z.J=Y.prototype;
Z.prototype.compileCallback=function(){if(!this.viewerCanRenderTemplates()){this.B={};if("TEMPLATE"==this.element.tagName){var a=this.element;if("content"in a)var b=a.content.cloneNode(!0);else{b=a.ownerDocument.createDocumentFragment();var c=b.ownerDocument.createDocumentFragment();for(a=a.firstChild;a;a=a.nextSibling)c.appendChild(a.cloneNode(!0));b.appendChild(c)}Lc(this,b);c=this.element.ownerDocument.createElement("div");c.appendChild(b);b=c.innerHTML}else b="SCRIPT"==this.element.tagName?this.element.textContent:
"";this.D=b;try{Ic.parse(this.D,void 0)}catch(d){F().error("amp-mustache",d.message,this.element)}}};function Lc(a,b){var c=b.querySelectorAll("template");Nb(c,function(b,c){c="__AMP_NESTED_TEMPLATE_"+c;a.B[c]=b.outerHTML;var d=a.element.ownerDocument.createTextNode("{{{"+c+"}}}");b.parentNode.replaceChild(d,b)})}Z.prototype.setHtml=function(a){return Mc(this,a)};
Z.prototype.render=function(a){var b=a;"object"===typeof a&&(b=Object.assign({},a,this.B));a=Ic.render(this.D,b,void 0);return Mc(this,a)};function Mc(a,b){b=a.C.purifyHtml("<div>"+b+"</div>").firstElementChild;return a.unwrap(b)}(function(a){a.registerTemplate("amp-mustache",Z)})(self.AMP);
})});

//# sourceMappingURL=amp-mustache-0.2.js.map
