(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"2004252135000",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ka=b.prototype}
function ia(a){for(var b=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ja=ia(this);function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function p(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma="";
function r(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=p(c.location.originalHash||c.location.hash);d=d.spt;var g=p(c.location.search);ma||(ma=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"012004252135000");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,esm:!1,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"2004252135000",
rtvVersion:ma,singlePassType:d};c=b.__AMP_MODE=c}return c};var na=Object.prototype.toString;function v(a){return a?Array.prototype.slice.call(a):[]}function w(a){return"[object Object]"===na.call(a)};var x=self.AMP_CONFIG||{},oa=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var y={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:x.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:x.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl||pa("amp-geo-api")};function qa(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var ra=self.__AMP_LOG;function z(){if(!ra.user)throw Error("failed to call initLogConstructor");return ra.user}function A(){if(ra.dev)return ra.dev;throw Error("failed to call initLogConstructor");}
function B(a,b,c,d,e){return z().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var C=Object.prototype.hasOwnProperty;function D(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function E(a){return a||{}}function F(a,b){if(C.call(a,b))return a[b]}
function sa(a,b){var c=10;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.C=b.s;a.N=b.d;if(d.includes(a.C))throw Error("Source object has a circular reference.");d.push(a.C);a.G!==a.C&&(a.N>c?Object.assign(a.G,a.C):Object.keys(a.C).forEach(function(a){return function(b){var c=a.C[b];if(C.call(a.G,b)){var d=a.G[b];if(w(c)&&w(d)){e.push({t:d,s:c,d:a.N+1});return}}a.G[b]=c}}(a)));a={C:a.C,G:a.G,N:a.N}}};function H(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var ta,ua="Webkit webkit Moz moz ms O o".split(" ");function va(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function wa(){return AMP.BaseElement.apply(this,arguments)||this}ha(wa,AMP.BaseElement);l=wa.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};l.renderOutsideViewport=function(){return!0};l.P=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};var xa;function J(){return xa?xa:xa=Promise.resolve(void 0)};function K(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function ya(){var a=100;this.va=a;this.W=this.aa=0;this.O=Object.create(null)}ya.prototype.has=function(a){return!!this.O[a]};ya.prototype.get=function(a){var b=this.O[a];if(b)return b.access=++this.W,b.payload};ya.prototype.put=function(a,b){this.has(a)||this.aa++;this.O[a]={payload:b,access:this.W};if(!(this.aa<=this.va)){A().warn("lru-cache","Trimming LRU cache");a=this.O;var c=this.W+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.aa--)}};var za=E({c:!0,v:!0,a:!0,ad:!0,action:!0}),Aa,Ba,Ca=/[?&]amp_js[^&]*/,Da=/[?&]amp_gsa[^&]*/,Ea=/[?&]amp_r[^&]*/,Fa=/[?&]amp_kit[^&]*/,Ga=/[?&]usqp[^&]*/;
function L(a){var b;Aa||(Aa=self.document.createElement("a"),Ba=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new ya));var c=b?null:Ba,d=Aa;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=
e.hostname;e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=r().test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,d);a=d}return a}
function Ha(a,b){var c=void 0===c?"source":c;B(null!=a,"%s %s must be available",b,c);var d=a;a=d;"string"==typeof a&&(a=L(a));var e;(e="https:"==a.protocol||"localhost"==a.hostname||"127.0.0.1"==a.hostname)||(a=a.hostname,e=a.length-10,e=0<=e&&a.indexOf(".localhost",e)==e);B(e||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}
function M(a){"string"==typeof a&&(a=L(a));return y.cdnProxyRegex.test(a.origin)}
function Ia(a){"string"==typeof a&&(a=L(a));if(!M(a))return a.href;var b=a.pathname.split("/");B(za[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);B(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Ca,"").replace(Da,"").replace(Ea,"").replace(Fa,"").replace(Ga,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Ja(a,b){"string"==typeof b&&(b=L(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=L(d));c=c.replace(/\\/g,"/");var e=L(c);c=H(c.toLowerCase(),e.protocol)?e.href:H(c,"//")?d.protocol+c:H(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Ma(a){var b=L(a),c=p(b.search);B(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};function Na(a,b){if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Oa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=p(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Oa(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){A().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};var Pa={},N=(Pa["ampdoc-fie"]={isTrafficEligible:function(){return!0},branches:[["21065001"],["21065002"]]},Pa);
function Qa(a){if(!Na(a,"ampdoc-fie"))return!1;a.__AMP_EXPERIMENT_BRANCHES=a.__AMP_EXPERIMENT_BRANCHES||{};for(var b in N)if(C.call(N,b)&&!C.call(a.__AMP_EXPERIMENT_BRANCHES,b))if(!N[b].isTrafficEligible||!N[b].isTrafficEligible(a))a.__AMP_EXPERIMENT_BRANCHES[b]=null;else if(!a.__AMP_EXPERIMENT_BRANCHES[b]&&Na(a,b)){var c=N[b].branches;a.__AMP_EXPERIMENT_BRANCHES[b]=c[Math.floor(Math.random()*c.length)]||null}return"21065002"===(a.__AMP_EXPERIMENT_BRANCHES?a.__AMP_EXPERIMENT_BRANCHES["ampdoc-fie"]:
null)};function Ra(a,b){var c=a.ownerDocument.defaultView,d=O(c),e=c!=d,f=Qa(d);e&&!f?b=Sa(c,b)?P(c,b):null:(a=Q(a),a=R(a),b=Sa(a,b)?P(a,b):null);return b}function Ta(a,b){var c=O(a);Sa(a,"bind");if(Qa(c)){var d=Q(a.document);Ua(R(d),d,"bind",function(){return b},!0)}else Ua(a,a,"bind",function(){return b}),P(a,"bind")}function S(a,b){a=O(a);return P(a,b)}function T(a,b){var c=Q(a);c=R(c);return P(c,b)}function Va(a,b){return Wa(R(a),b)}function O(a){return a.__AMP_TOP||(a.__AMP_TOP=a)}
function Q(a){return a.nodeType?S((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function R(a){a=Q(a);return a.isSingleDoc()?a.win:a}function P(a,b){Sa(a,b);var c=Xa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ua(a,b,c,d,e){var f=Xa(a),g=f[c];g||(g=f[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null});if(e||!g.ctor&&!g.obj)g.ctor=d,g.context=b,g.resolve&&P(a,c)}
function Ya(a,b){var c=Wa(a,b);if(c)return c;a=Xa(a);a[b]=Za();return a[b].promise}function Wa(a,b){var c=Xa(a)[b];if(c){if(c.promise)return c.promise;P(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Xa(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Sa(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Za(){var a=new K,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var $a=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function ab(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function bb(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function cb(a,b){bb(a.documentElement,function(){return!!a.body},b)}function db(a){return new Promise(function(b){return cb(a,b)})}function eb(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}
function fb(a,b){return a.closest?a.closest(b):eb(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function gb(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function hb(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function ib(a){H(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new K;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function jb(a,b,c){var d=Va(a,b);if(d)return d;var e=Q(a);return e.waitForBodyOpen().then(function(){return kb(e.win,c,e.win.document.head)}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS[c]?Ya(R(a),b):null})}function lb(a){var b=Ra(a,"bind");if(b)return Promise.resolve(b);b=a.ownerDocument.defaultView;var c=O(b);return b!==c?nb(b):jb(a,"bind","amp-bind")}
function kb(a,b,c){if(c){var d={};c=c.querySelectorAll("script[custom-element],script[custom-template]");for(var e=0;e<c.length;e++){var f=c[e];f=f.getAttribute("custom-element")||f.getAttribute("custom-template");d[f]=!0}d=Object.keys(d)}else d=[];if(!d.includes(b))return J();var g=S(a,"extensions");return g.waitForExtension(a,b)}
function nb(a){return db(a.document).then(function(){return kb(a,"amp-bind",a.document.head)}).then(function(){return a.__AMP_EXTENDED_ELEMENTS&&a.__AMP_EXTENDED_ELEMENTS["amp-bind"]?Ya(a,"bind"):null})};function ob(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function pb(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function qb(a,b){var c=20;c=void 0===c?5:c;if(!isFinite(c)||0>c)throw Error("Invalid depth: "+c);if(a===b)return!0;for(a=[{a:a,b:b,depth:c}];0<a.length;){var d=a.shift();b=d.a;c=d.b;d=d.depth;if(0<d){if(typeof b!==typeof c)return!1;if(Array.isArray(b)&&Array.isArray(c)){if(b.length!==c.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:c[e],depth:d-1});continue}else if(b&&c&&"object"===typeof b&&"object"===typeof c){var f=Object.keys(b),g=Object.keys(c);if(f.length!==g.length)return!1;for(e=
0;e<f.length;e++){var k=f[e];a.push({a:b[k],b:c[k],depth:d-1})}continue}}if(b!==c)return!1}return!0};function rb(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.token?void 0:c.token,k=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Ha(b.getAttribute("src"),b);var h=S(a.win,"batched-xhr");return sb(b,e,f).then(function(a){void 0!==g&&(a.fetchOpt.method="POST",a.fetchOpt.headers={"Content-Type":"application/x-www-form-urlencoded"},a.fetchOpt.body={ampViewerAuthToken:g});return h.fetchJson(a.xhrUrl,a.fetchOpt)}).then(function(b){return S(a.win,
"xhr").xssiJson(b,k)}).then(function(a){if(null==a)throw Error("Response is undefined.");return ob(a,d||".")}).catch(function(a){throw z().createError("failed fetching JSON data",a);})}
function sb(a,b,c){var d=a.getAttribute("src"),e=Ra(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(d){if(1==b){var f=e.collectUnwhitelistedVarsSync(a);if(0<f.length)throw z().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(f.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var k={};a.hasAttribute("credentials")&&(k.credentials=a.getAttribute("credentials"));
c&&(k.cache="reload");return{xhrUrl:d,fetchOpt:k}})};function tb(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function ub(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function vb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function wb(a){var b=a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?jb(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){B(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function xb(a){a=AMP.BaseElement.call(this,a)||this;a.R=void 0;a.$=new K;return a}ha(xb,AMP.BaseElement);l=xb.prototype;l.getLayoutPriority=function(){return 1};l.isAlwaysFixed=function(){return!0};l.isLayoutSupported=function(){return!0};
l.buildCallback=function(){var a=this;va(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&lb(b).then(function(a){a.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&Cb(this,!0);this.registerAction("refresh",function(){B(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');Cb(a,!1,!0)})};
l.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&Cb(this,!1);else{var b=this.P();A().error(b,"ampdoc must be visible before mutation.")}};l.renderOutsideViewport=function(){return!0};l.parseAndUpdate=function(){return void 0===this.R&&(this.R=Db(this),null!==this.R)?Eb(this,this.R,!0):J()};
function Db(a){var b=a.element.children;if(0==b.length)return null;var c=a.P();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return hb(d)?pb(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function Fb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src"),g=L(Ia(f)).origin!==L(Ia(e.win.location)).origin,k=g&&!b?1:2;return wb(d).then(function(b){return rb(e,a.element,{urlReplacement:k,refresh:c,token:b}).catch(function(b){b=b?tb(a.win,"amp-state.error",E({response:b.response})):null;var c=Ra(d,"action");c.trigger(d,"fetch-error",b,1)})})}
function Cb(a,b,c){b||(a.$=new K);var d=a.$;a.getAmpDoc().whenFirstVisible().then(function(){return Fb(a,b,c)}).then(function(c){return Eb(a,c,b)}).then(function(){return d.resolve()}).catch(function(a){d.resolve();throw a;})}l.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.$.promise:J()};
function Eb(a,b,c){if(void 0===b||null===b)return J();var d=B(a.element.id,"<amp-state> must have an id.");return lb(a.element).then(function(a){var e=D();e[d]=b;a.setState(e,{skipEval:c,skipAmpState:!c})})}l.P=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var Gb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function Hb(a){for(var b=[],c;c=Gb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new Ib(b)}
function Ib(a){B(0<a.length,"Srcset must have at least one source");this.M=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}B(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?Jb:Kb);this.ra=b}
Ib.prototype.select=function(a,b){if(this.ra){b*=a;a=this.M;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,k=Math.abs(g-b);if(k<=1.1*d||1.2<b/e)c=f,d=k,e=g;else break}b=c}else{a=this.M;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.M[b].url};Ib.prototype.getUrls=function(){return this.M.map(function(a){return a.url})};
Ib.prototype.stringify=function(a){for(var b=[],c=this.M,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.ra?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function Jb(a,b){B(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function Kb(a,b){B(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var Lb={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},Mb={width:null,height:null},Nb={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null},SELECT:{autofocus:null,disabled:null,
multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},Ob={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function Pb(a){this.ta=a}Pb.prototype.canBind=function(a,b){return void 0!==Qb(this,a,b)};
Pb.prototype.isResultValid=function(a,b,c){var d=Qb(this,a,b);d&&d.alternativeName&&(d=Qb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&F(Ob,b)){if("srcset"===b){try{var e=Hb(c)}catch(n){return z().error("amp-bind","Failed to parse srcset: ",n),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{var g=f[a];b=d;if(g){if(/__amp_source_origin/.test(g)){b=!1;break a}if(b=b.allowedProtocols)if(g=/^([^:\/?#.]+):[\s\S]*$/.exec(g),null!==g&&(g=g[1].toLowerCase().trim(),
!C.call(b,g))){b=!1;break a}}b=!0}if(!b)return!1}}var k=d.blacklistedValueRegex;if(c&&k){var h=new RegExp(k,"i");if(h.test(c))return!1}return!0};function Qb(a,b,c){if(H(c,"aria-"))return null;if(!F(Ob,c)||a.ta){var d=F(Lb,c);if(void 0!==d)return d;var e=F(Mb,c);if(H(b,"AMP-")&&void 0!==e)return e;var f=F(Nb,b);if(f)return f[c]}};var Rb=!1;function Sb(a){if(!Rb){Rb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(H(g,"--"))f=g;else{ta||(ta=D());var k=ta[g];if(!k){k=g;if(void 0===f[g]){var h=g;h=h.charAt(0).toUpperCase()+h.slice(1);b:{for(var n=0;n<ua.length;n++){var m=ua[n]+h;if(void 0!==f[m]){h=m;break b}}h=""}void 0!==f[h]&&(k=h)}ta[g]=k}f=k}f&&(H(f,"--")?d.style.setProperty(f,e):d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ja.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Tb=/nochunking=1/.test(self.location.hash),Ub=J();function Vb(a,b){if(Tb)Ub.then(b);else{var c=Wb,d=Q(a),e=R(d);Ua(e,d,"chunk",c);T(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Y=a}function Xb(a,b){if("run"!=a.state){a.state="run";try{a.Y(b)}catch(c){throw a.la(),c;}}}V.prototype.P=function(){return this.Y.displayName||this.Y.name};V.prototype.la=function(){};V.prototype.ja=function(){return!1};V.prototype.pa=function(){return!1};function W(a,b,c){V.call(this,a);this.fa=c}
ha(W,V);W.prototype.la=function(){Sb(self.document)};W.prototype.ja=function(){return this.fa.ampdoc.isVisible()};W.prototype.pa=function(){return this.fa.ga};
function Wb(a){var b=this;this.ampdoc=a;this.h=a.win;this.J=new U;this.ea=this.ha.bind(this);this.K=0;this.T=!1;this.ua=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ha(null)});this.ga=!1;Ya(R(a),"viewer").then(function(){b.ga=!0});a.onVisibilityChanged(function(){a.isVisible()&&Yb(b)})}Wb.prototype.run=function(a,b){var c=new V(a);this.J.enqueue(c,b);Yb(this)};
Wb.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.J.enqueue(a,Number.POSITIVE_INFINITY);Yb(this)};function Zb(a,b){for(var c=a.J.peek();c&&"not_run"!==c.state;)a.J.dequeue(),c=a.J.peek();c&&b&&a.J.dequeue();return c}Wb.prototype.ha=function(a){var b=this,c=Zb(this,!0);if(!c)return this.T=!1,this.K=0,!1;try{var d=Date.now();Xb(c,a)}finally{Ub.then().then().then().then().then().then().then().then().then(function(){b.T=!1;b.K+=Date.now()-d;Yb(b)})}return!0};
function $b(a){a.ua&&5<a.K?(a.K=0,ac(a)):Ub.then(function(){a.ea(null)})}function Yb(a){if(!a.T){var b=Zb(a);b&&(b.ja()?(a.T=!0,$b(a)):b.pa()&&a.h.requestIdleCallback?bc(a.h,a.ea):ac(a))}}function ac(a){a.h.postMessage("amp-macro-task","*")}function bc(a,b){function c(f){if(f.timeRemaining()<d){var g=2E3-(Date.now()-e);0>=g||f.didTimeout?b(f):a.requestIdleCallback(c,{timeout:g})}else b(f)}var d=15,e=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function cc(){this.F=D();this.j=null}l=cc.prototype;l.get=function(a){a=this.F[a];return null==a?null:a};l.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new K,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=D());this.j[a]=b}return b.promise};
l.signal=function(a,b){if(null==this.F[a]){var c=b||Date.now();this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};l.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};l.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function dc(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var k=f;f=null;b.apply(null,k)}}var d=0,e=0,f=null;return function(b){for(var g=[],h=0;h<arguments.length;++h)g[h-0]=arguments[h];e=a.Date.now();f=g;d||(d=a.setTimeout(c,5E3))}};function ec(a,b,c){var d="ww",e=r().esm?".mjs":".js";if(b){var f=a.protocol+"//"+a.host;"about:"==a.protocol&&(f="");a=f+"/dist"}else a=y.cdn;return b?a+"/"+d+e:c?a+"/rtv/"+r().rtvVersion+"/"+d+e:a+"/"+d+e};function fc(a){var b=this;this.h=a;this.Ea=S(a,"xhr");var c=a.location;r().test&&a.testLocation&&(c=a.testLocation);var d=r().localDev||r().test,e=!d,f=ec(c,d,e);this.ba=null;this.ia=this.Ea.fetchText(f,{ampCors:!1,bypassInterceptorForDev:r().localDev}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c+"\n//# sourceurl="+f],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.ba=new a.Worker(d);b.ba.onmessage=b.Ca.bind(b)});this.S={};this.wa=0;this.sa=[a]}
function gc(a,b,c,d){return a.ia.then(function(){return new Promise(function(e,f){var g=a.wa++;a.S[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.sa.indexOf(e);var k=0<=f?f:a.sa.push(e)-1;a.ba.postMessage({method:b,args:c,scope:k,id:g})})})}fc.prototype.Ca=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.S[b];d?(d.resolve(c),delete this.S[b]):A().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
fc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.S).length};fc.prototype.Fa=function(){return this.ia};function hc(a){var b=["\u26a14email","amp4email"],c=a.documentElement,d=b.some(function(a){return c.hasAttribute(a)});return d};function ic(){var a=1.5,b=jc(a);return function(a){return setTimeout(a,b())}}function jc(a){var b=a||2,c=0;return function(){var a=Math.pow(b,c++);var e=a*(e||.3)*Math.random();.5<Math.random()&&(e*=-1);a+=e;return 1E3*a}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function kc(a){kc=ic();return kc(a)}function lc(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var mc;
function nc(a,b){try{if(a)if(void 0!==a.message){a=qa(a);var c=!0}else{var d=a;a=Error(lc(d));a.origError=d}else a=Error("Unknown error");c||!r().localDev||r().test||setTimeout(function(){var b=Error("_reported_ Error reported incorrectly: "+a);throw b;});if(!a.reported){a.reported=!0;var e=b||a.associatedElement;e&&e.classList&&(e.classList.add("i-amphtml-error"),r().development&&(e.classList.add("i-amphtml-element-error"),e.setAttribute("error-message",a.message)));if(self.console){var f=console.error||
console.log;a.messageArray?f.apply(console,a.messageArray):e?f.call(console,a.message,e):r().minified?f.call(console,a.message):f.call(console,a.stack)}e&&e.za&&e.za("amp:error",a.message);oc.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(g){setTimeout(function(){throw g;})}}
function oc(a,b,c,d,e){var f=this;this&&this.document&&Sb(this.document);if(!(r().localDev||r().development||r().test)){var g=!1;try{g=pc()}catch(h){}if(!(g&&.01<Math.random())){var k=qc(a,b,c,d,e,g);k&&kc(function(){try{return rc(f,k).catch(function(){})}catch(h){}})}}}function rc(a,b){return sc(a,b).then(function(a){if(!a){var c=new XMLHttpRequest;c.open("POST",.1>Math.random()?y.betaErrorReporting:y.errorReporting,!0);c.send(JSON.stringify(b))}})}
function sc(a,b){var c=S(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);a=c.getSingleDoc();if(!a.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var d=T(a,"viewer");return d.hasCapability("errorReporter")?d.isTrustedViewer().then(function(a){if(!a)return!1;d.sendMessage("error",E({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,jse:b.jse}));return!0}):Promise.resolve(!1)}
function qc(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var k=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var h=!(self&&self.window),n=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||h)if(k=!0,.001<n)return;var m=0<=a.indexOf("\u200b\u200b\u200b");if(!(m&&.1<n)){g=Object.create(null);g.v=r().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=m?"1":"0";g.ex=k?"1":"0";g.dw=h?"1":"0";var q="1p";self.context&&
self.context.location?(g["3p"]="1",q="3p"):r().runtime&&(q=r().runtime);r().singlePassType&&(g.spt=r().singlePassType);g.rt=q;"inabox"===q&&(g.adid=r().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var mb=
self.AMP.viewer.getResolvedViewerUrl(),G=self.AMP.viewer.maybeGetMessagingOrigin();mb&&(g.rvu=mb);G&&(g.mso=G)}mc||(mc=tc());g.jse=mc;var u=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var t in f)u.push(t+"="+(f[t]?"1":"0"));g.exps=u.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),m||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";
g.ae=X.join(",");g.fr=self.location.originalHash||self.location.hash;b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function pc(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!M(a[b].src.toLowerCase()))return!0;return!1}
function tc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(H(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(H(b,"Error: message"))return"Chrome"}return"unknown"};function uc(a,b,c){var d=self.location;Ma(c);var e=M(d),f=L(Ia(d));if("href"==b&&!H(c,"#"))return Ja(c,f);if("src"==b)return"amp-img"==a?vc(c,f,e):Ja(c,f);if("srcset"==b){try{var g=Hb(c)}catch(k){return z().error("URL-REWRITE","Failed to parse srcset: ",k),c}return g.stringify(function(a){return vc(a,f,e)})}return c}
function vc(a,b,c){a=L(Ja(a,b));return"data:"==a.protocol||M(a)||!c?a.href:y.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};function wc(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function xc(a,b){var c=wc,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function yc(a){return new Promise(function(b){xc(a,b)})};var zc=/^(i?-)?amp(html)?-/,Ac={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0}},Bc=D({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state","is-layout-container"],"AMP-SELECTOR":["selected"]}),Cc=["AMP-LIST"];
function Dc(a,b){var c=this;this.ampdoc=a;this.h=a.win;this.B=b||a.win;this.X=[];this.Aa=dc(this.h,function(){c.X.length=0});this.H=[];this.D=D();this.Z=T(a,"history");this.ma=[];this.I=1E3;this.ka=T(a,"mutator");this.w=D();this.Da=S(this.h,"timer");this.qa=null;this.V=T(this.ampdoc,"viewer");this.V.onMessageRespond("premutate",this.Ba.bind(this));this.na=a.whenFirstVisible().then(function(){if(b){var c=b.document;return yc(c).then(function(){return c})}return a.whenReady().then(function(){return a.getRootNode()})});
this.L=this.na.then(function(a){return Ec(c,a)});this.da=new K;this.U=null;this.oa=new cc;var d=self.AMP;d.printState=d.printState||this.ya.bind(this);d.setState=d.setState||function(a){return c.setState(a)};d.eval=d.eval||this.xa.bind(this)}Dc.installInEmbedWindow=function(a,b){Ta(a,new Dc(b,a))};l=Dc.prototype;l.signals=function(){return this.oa};
l.setState=function(a,b){var c=this;b=void 0===b?{}:b;A().info("amp-bind","setState (init=%s):",b.skipEval,a);try{sa(this.w,a)}catch(d){z().error("amp-bind","Failed to merge result from AMP.setState().",d)}if(b.skipEval)return J();a=this.L.then(function(){return Fc(c)}).then(function(a){return Gc(c,a,{skipAmpState:b.skipAmpState,constrain:b.constrain})});r().test&&a.then(function(){Hc(c,"amp:bind:setState")});return this.U=a};
l.invoke=function(a){var b=a,c=b.args,d=b.event,e=b.method,f=b.sequenceId,g=b.tagOrTarget;if(this.X.includes(f))return z().error("amp-bind","One state action allowed per event."),J();this.X.push(f);this.Aa();if(b=c.__AMP_OBJECT_STRING__)switch(this.I=Math.min(2E3,Math.max(1E3,this.I+500)),this.oa.signal("FIRST_MUTATE"),c={},d&&d.detail&&(c.event=d.detail),e){case "setState":return this.setStateWithExpression(b,c);case "pushState":return this.pushStateWithExpression(b,c);default:return Promise.reject(A().createError("Unrecognized method: %s.%s",
g,e))}else z().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return J()};l.setStateWithExpression=function(a,b){var c=this;return Ic(this,a,b).then(function(a){return Jc(c,a)})};l.setStateWithObject=function(a){return(a=Kc(a))?Jc(this,a):Promise.reject("Invalid state")};
function Jc(a,b){A().info("amp-bind","setState:",b);a.U=a.setState(b).then(function(){return Lc(a)}).then(function(b){b&&a.Z.replace(b)});return a.U}l.pushStateWithExpression=function(a,b){var c=this;A().info("amp-bind","pushState:",a);return Ic(this,a,b).then(function(a){function b(){return c.setState(d)}var d=D();Object.keys(a).forEach(function(a){d[a]=Kc(c.w[a])});return c.setState(a).then(function(){return Lc(c)}).then(function(a){c.Z.push(b,a)})})};
function Lc(a){var b=E({data:E({"amp-bind":a.w}),title:a.B.document.title});return a.V.isEmbedded()?a.V.isTrustedViewer().then(function(a){return a?b:null}):Promise.resolve(b)}l.rescan=function(a,b,c){var d=this;c=void 0===c?{}:c;var e=c.fast?this.da.promise:this.L;return e.then(function(){return d.Da.timeoutPromise(c.timeout||2E3,Mc(d,a,b,c),"Timed out waiting for amp-bind to rescan.")})};
function Mc(a,b,c,d){A().info("amp-bind","rescan: ",b,c,d);var e=d.fast?Nc(a,b,c):Oc(a,b,c);return e.then(function(){if(d.update)return Fc(a).then(function(c){return Gc(a,c,{constrain:b})})})}
function Nc(a,b,c){var d=Pc(a,c),e=[],f=b.filter(function(a){return a.hasAttribute("i-amphtml-binding")});b.forEach(function(a){a=a.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,a)});var g=a.I-a.numberOfBindings();for(b=0;b<f.length&&!Qc(a,f[b],g-e.length,e);b++);d.then(function(b){A().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-b,a.numberOfBindings())});return 0<e.length?Rc(a,e):J()}
l.getState=function(a){a=a?ob(this.w,a):void 0;return w(a)||Array.isArray(a)?Kc(a):a};l.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.na.then(function(d){var e=d.querySelector("#"+String(c).replace($a,ab));if(!e)throw Error("#"+c+" does not exist.");return ib(e).then(function(a){return a.getImpl(!0)}).then(function(a){return a.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
l.getStateValue=function(a){a=ob(this.w,a);return void 0===a||null===a?null:w(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function Ec(a,b){var c=!hc(a.B.document);a.qa=new Pb(c);return Y(a,"bind.init",[c]).then(function(){return Promise.all([Sc(a).then(function(){return a.da.resolve()}),Tc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(b){return Uc(a,b)})}).then(function(){var a=b.querySelectorAll("AMP-STATE"),c=!1,f=v(a).map(function(a){return ib(a).then(function(){return a.getImpl(c)}).then(function(a){return a.parseAndUpdate()})});return Promise.all(f)}).then(function(){a.V.sendMessage("bindReady",
void 0);Hc(a,"amp:bind:initialize");if(r().development)return Fc(a).then(function(b){return Vc(a,b)})})}l.numberOfBindings=function(){return this.H.reduce(function(a,b){return a+b.boundProperties.length},0)};l.Ia=function(a){this.I=a};l.Ga=function(){return this.Z};
l.Ba=function(a){var b=this,c=[];return this.L.then(function(){Object.keys(a.state).forEach(function(d){b.ma.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&z().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};l.addOverridableKey=function(a){this.ma.push(a)};
function Sc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];gb(b,function(a){var b=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});c.push({id:a.getAttribute("id"),argumentNames:b,expressionString:a.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Y(a,"bind.addMacros",[c]).then(function(a){a.forEach(function(a,c){Wc(a,"amp-bind: Parsing amp-bind-macro failed.",b[c])});return c.length})}
function Tc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(b){var c=r().localDev&&!r().test?Number.POSITIVE_INFINITY:a.I-a.numberOfBindings();return Xc(a,b,c).then(function(b){var c=b.bindings,d=b.limitExceeded;d&&A().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.I);return c})});return Promise.all(c).then(function(b){b=Array.prototype.concat.apply([],b);return 0<b.length?Rc(a,b):0})}
function Rc(a,b){return Y(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(b){var d=a.D[b];0<d.length&&Wc(c[b],'amp-bind: Expression compile error in "'+b+'".',d[0])});return b.length})}
function Pc(a,b){if(!b.length)return Promise.resolve(0);ub(a.H,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];ub(e,function(a){for(var c=0;c<b.length;c++)if(b[c].contains(a))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Y(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Xc(a,b,c){function d(){var b=f.currentNode;if(!b)return!0;if(b.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();var d=c-e.length;Qc(a,b,d,e)&&(g=!0);if(Cc.includes(b.nodeName))a:{b=f;for(var n=b.currentNode;n;n=b.parentNode())if(n=b.nextSibling()){b=n;break a}b=null}else b=f.nextNode();var m=b;return!m||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(b){function c(f){var h=!1;if(f&&!f.didTimeout)for(;1<
f.timeRemaining()&&!h;)h=d();else{var k=250;for(f=0;f<k&&!h;f++)h=d()}h?b({bindings:e,limitExceeded:g}):Vb(a.ampdoc,c)}Vb(a.ampdoc,c)})}function Qc(a,b,c,d){var e=!1,f=Yc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.H.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(c){var e=c,f=e.expressionString;d.push({tagName:g,property:e.property,expressionString:f});a.D[f]||(a.D[f]=[]);a.D[f].push(b)});return e}
function Yc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,k=a,h=d[e];var n=b;var m=n.tagName,q=h.name;if(2<q.length&&"["===q[0]&&"]"===q[q.length-1])g=q.substr(1,q.length-2);else if(H(q,"data-amp-bind-")&&(g=q.substr(14),n.hasAttribute("["+g+"]"))){n=null;break a}if(g){if(k.qa.canBind(m,g)){n={property:g,expressionString:h.value};break a}g=z().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,m);Z(g,n)}n=null}n&&c.push(n)}return c}
function Ic(a,b,c){return a.L.then(function(){Object.assign(c,a.w);return Y(a,"bind.evaluateExpression",[b,c])}).then(function(a){var b=a.result;if(a=a.error)throw Wc(a,"amp-bind: Expression eval failed.");return b})}
function Fc(a){var b=Y(a,"bind.evaluateBindings",[a.w]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.D[b];if(0<c.length){var d=e[b],f=z().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",b,d.message);f.stack=d.stack;Z(f,c[0])}});A().info("amp-bind","evaluation:",c);return c})}
function Vc(a,b){var c=void 0===c?null:c;var d=void 0===d?!0:d;var e={};a.H.forEach(function(a){var f=a.element;a=a.boundProperties;c&&!Zc(c,f)||a.forEach(function(a){var c=b[a.expressionString];if(void 0!==c){var g=a.property,m=Bc[f.tagName];if(m&&m.includes(g))c=null;else{switch(g){case "text":g=f.textContent;c=String(c);m=g.trim()===c.trim();break;case "class":g=[];for(m=0;m<f.classList.length;m++){var q=f.classList[m];zc.test(q)||g.push(q)}q=[];Array.isArray(c)?q=c:"string"===typeof c?(m=c.trim(),
0<m.length&&(q=m.split(" "))):(m=z().createError('%s: "%s" is not a valid result for [class].',"amp-bind",c),Z(m,f));b:{m=g;var k=q;if(m.length!==k.length)m=!1;else{q=(Array.isArray(m)?m:v(m)).sort();k=(Array.isArray(k)?k:v(k)).sort();for(var G=0;G<m.length;G++)if(q[G]!==k[G]){m=!1;break b}m=!0}}break;default:g=f.getAttribute(g),m=!0===c?""===g:!1===c?null===g:"number"===typeof c?Number(g)===c:g===c}c=m?null:{expected:c,actual:g}}var u=c;if(u){c=f.tagName;g=a.property;a=a.expressionString;m=u;q=m.expected;
var t=m.actual;e[c+"["+g+"]"+q+":"+t]=!0;d&&z().warn("amp-bind","Default value ("+t+") does not match first result ("+(q+") for <"+c+" ["+g+']="')+(a+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(e)}function Zc(a,b){for(var c=0;c<a.length;c++)if(a[c].contains(b))return!0;return!1}
function $c(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||qb(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}function Gc(a,b,c){var d=[];a.H.forEach(function(e){c.skipAmpState&&"AMP-STATE"===e.element.tagName||(!c.constrain||c.constrain.some(function(a){return a.contains(e.element)}))&&d.push(ad(a,b,e))});return Promise.all(d)}
function ad(a,b,c){var d=c.element,e=$c(c.boundProperties,b);return 0===e.length?J():a.ka.mutateElement(d,function(){var b=D(),c,k;e.forEach(function(e){var f=e,g=f.boundProperty,h=f.newValue;f=g.property;a:{g=g.property;var n=d.tagName;switch(g){case "defaulttext":d.textContent=String(h);break;case "text":g=String(h);"TITLE"===n&&d.parentNode===a.B.document.head&&(a.B.document.title=g);"TEXTAREA"===n?d.value=g:d.textContent=g;break;case "class":g=[];for(var u=0;u<d.classList.length;u++){var t=d.classList[u];
zc.test(t)&&g.push(t)}Array.isArray(h)||"string"===typeof h?d.setAttribute("class",g.concat(h).join(" ")):null===h?d.setAttribute("class",g.join(" ")):(g=z().createError('%s: "%s" is not a valid result for [class].',"amp-bind",h),Z(g,d));break;default:var yb="INPUT"===n&&g in d,I=d.getAttribute(g);n=!1;if("boolean"===typeof h){if(yb&&d[g]!==h&&(d[g]=h,n=!0),h&&""!==I?(d.setAttribute(g,""),n=!0):h||null===I||(d.removeAttribute(g),n=!0),n&&"OPTION"===d.tagName&&"selected"===g&&h&&S(a.h,"platform").isSafari()&&
(u=fb(d,"select")))t=v(u.options).indexOf(d),0<=t&&(u.selectedIndex=t)}else if("object"===typeof h&&null!==h)n=!0;else if(h!==I)b:{I=String(h);try{u=d.tagName.toLowerCase();t=g.toLowerCase();var Ka="src"==t||"href"==t||"xlink:href"==t||"srcset"==t?uc(u,t,I):I;if(M(self.location)&&"a"===u&&"href"===t){var zb=d.getAttribute(t),Ab="#"===Ka[0],Bb=zb&&"#"===zb[0];Ab&&!Bb?(d.__AMP_ORIGINAL_TARGET_VALUE_||(d.__AMP_ORIGINAL_TARGET_VALUE_=d.getAttribute("target")),d.removeAttribute("target")):Bb&&!Ab&&d.setAttribute("target",
d.__AMP_ORIGINAL_TARGET_VALUE_||"_top")}yb&&(d[t]=Ka);d.setAttribute(t,Ka);n=!0;break b}catch(bd){u=z().createError('%s: "%s" is not a valid result for [%]',"amp-bind",I,g,bd),Z(u,d)}n=!1}if(n){g={name:g,value:h};break a}}g=null}var La=g;La&&(b[La.name]=La.value,"width"==f?c="number"===typeof h&&isFinite(h)?Number(h):c:"height"==f&&(k="number"===typeof h&&isFinite(h)?Number(h):k));(h=Ac[d.tagName])&&h[f]&&(f="OPTION"===d.tagName?fb(d,"SELECT"):d)&&(h=tb(a.B,"amp:form-value-change",null,{bubbles:!0}),
f.dispatchEvent(h))});void 0===c&&void 0===k||a.ka.forceChangeSize(d,k,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(n){var h=z().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(b),n);Z(h,d)}})}function Uc(a,b){b=b.target;var c=b.parentNode;c&&Cc.includes(c.nodeName)||(A().info("amp-bind","dom_update:",b),Oc(a,[b],[b],"dom_update.end").then(function(){Hc(a,"amp:bind:rescan-template")}))}
function Oc(a,b,c,d){d=void 0===d?"rescan.slow":d;var e=0;return Pc(a,c).then(function(c){e=c;return Tc(a,b)}).then(function(b){A().info("amp-bind","%s: delta=%s, total=%s",d,b-e,a.numberOfBindings())})}function Y(a,b,c){var d=a.h;a=a.B;if(d.Worker){var e=O(d);Ua(e,e,"amp-worker",fc);d=S(d,"amp-worker");b=gc(d,b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}function Wc(a,b,c){b=z().createError("%s %s",b,a.message);b.stack=a.stack;Z(b,c);return b}
function Z(a,b){r().test||nc(a,b)}function Kc(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){A().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
l.ya=function(a){if(a)if("string"==typeof a){var b=ob(this.w,a);z().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=z().assertElement(a),cd(this,b)):z().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else z().info("amp-bind",this.w)};
function cd(a,b){var c=vb(a.H,function(a){return a.element==b});if(0>c)z().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.H[c].boundProperties;e.forEach(function(b){d.push(Ic(a,b.expressionString,a.w))});Promise.all(d).then(function(a){var b=D();e.forEach(function(c,d){b[c.property]=a[d]});z().info("amp-bind",b)})}}l.xa=function(a){Ic(this,a,this.w).then(function(a){z().info("amp-bind",a)})};l.Ha=function(){return this.L};l.Ja=function(){return this.U};
function Hc(a,b){if(r().test){if("function"===typeof a.B.Event)var c=new Event(b,{bubbles:!0,cancelable:!0});else c=a.B.document.createEvent("Event"),c.initEvent(b,!0,!0);a.B.dispatchEvent(c)}};(function(a){a.registerServiceForDoc("bind",Dc);a.registerElement("amp-state",xb);a.registerElement("amp-bind-macro",wa)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
